version : '3'
services : 

    #RESTFUL-API
    api : 
        image: 'webtoor/test-indodax-go:1.0'
        container_name: api
        restart: on-failure
        volumes:
            - ./:/app/
        env_file:
            - ./.env
        ports:
            - "8080:8080"
            - "443:443"
        depends_on:
            - db
        networks:
            - go-api
    
    #DB-MYSQL
    db:
        image: 'mysql:5.7.22'
        container_name: db
        restart: always
        ports :
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: ${SERVICE_TAGS}
            SERVICE_NAME: ${SERVICE_NAME}
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - go-api

    #PHPMYADMIN        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "9092:80"
        environment:
            PMA_HOST: godockerDB
        networks:
            - go-api
networks:
    go-api: